async function updateMaterials(pool, warehouse_id) {
	await pool.query(`
  UPDATE materials 
  SET 
    a1_6 = ((SELECT a1_6start FROM materials WHERE warehouse_id = ?) - (SELECT SUM(a1_6 * number) FROM products JOIN allproducts ON products.allproduct_id=allproducts.id WHERE warehouse_id = ? )) ,
    a1_8 = ((SELECT a1_8start FROM materials WHERE warehouse_id = ?) - (SELECT SUM(a1_8 * number) FROM products JOIN allproducts ON products.allproduct_id=allproducts.id WHERE warehouse_id = ? )) ,
    a1_10 = ((SELECT a1_10start FROM materials WHERE warehouse_id = ?) - (SELECT SUM(a1_10 * number) FROM products JOIN allproducts ON products.allproduct_id=allproducts.id WHERE warehouse_id = ? )) ,
    a1_12 = ((SELECT a1_12start FROM materials WHERE warehouse_id = ?) - (SELECT SUM(a1_12 * number) FROM products JOIN allproducts ON products.allproduct_id=allproducts.id WHERE warehouse_id = ? )) ,
    a1_14 = ((SELECT a1_14start FROM materials WHERE warehouse_id = ?) - (SELECT SUM(a1_14 * number) FROM products JOIN allproducts ON products.allproduct_id=allproducts.id WHERE warehouse_id = ? )) ,
    a1_16 = ((SELECT a1_16start FROM materials WHERE warehouse_id = ?) - (SELECT SUM(a1_16 * number) FROM products JOIN allproducts ON products.allproduct_id=allproducts.id WHERE warehouse_id = ? )) ,
    a1_18 = ((SELECT a1_18start FROM materials WHERE warehouse_id = ?) - (SELECT SUM(a1_18 * number) FROM products JOIN allproducts ON products.allproduct_id=allproducts.id WHERE warehouse_id = ? )) ,
    a1_20 = ((SELECT a1_20start FROM materials WHERE warehouse_id = ?) - (SELECT SUM(a1_20 * number) FROM products JOIN allproducts ON products.allproduct_id=allproducts.id WHERE warehouse_id = ? )) ,
    a1_22 = ((SELECT a1_22start FROM materials WHERE warehouse_id = ?) - (SELECT SUM(a1_22 * number) FROM products JOIN allproducts ON products.allproduct_id=allproducts.id WHERE warehouse_id = ? )) ,
    a1_25 = ((SELECT a1_25start FROM materials WHERE warehouse_id = ?) - (SELECT SUM(a1_25 * number) FROM products JOIN allproducts ON products.allproduct_id=allproducts.id WHERE warehouse_id = ? )) ,
    a1_28 = ((SELECT a1_28start FROM materials WHERE warehouse_id = ?) - (SELECT SUM(a1_28 * number) FROM products JOIN allproducts ON products.allproduct_id=allproducts.id WHERE warehouse_id = ? )) ,
    a3_6 = ((SELECT a3_6start FROM materials WHERE warehouse_id = ?) - (SELECT SUM(a3_6 * number) FROM products JOIN allproducts ON products.allproduct_id=allproducts.id WHERE warehouse_id = ? )) ,
    a3_8 = ((SELECT a3_8start FROM materials WHERE warehouse_id = ?) - (SELECT SUM(a3_8 * number) FROM products JOIN allproducts ON allproducts.id=products.allproduct_id WHERE warehouse_id = ? )) ,
    a3_10 = ((SELECT a3_10start FROM materials WHERE warehouse_id = ?) - (SELECT SUM(a3_10 * number) FROM products JOIN allproducts ON allproducts.id=products.allproduct_id WHERE warehouse_id = ? )) ,
    a3_12 = ((SELECT a3_12start FROM materials WHERE warehouse_id = ?) - (SELECT SUM(a3_12 * number) FROM products JOIN allproducts ON allproducts.id=products.allproduct_id WHERE warehouse_id = ? )) ,
    a3_14 = ((SELECT a3_14start FROM materials WHERE warehouse_id = ?) - (SELECT SUM(a3_14 * number) FROM products JOIN allproducts ON allproducts.id=products.allproduct_id WHERE warehouse_id = ? )) ,
    a3_16 = ((SELECT a3_16start FROM materials WHERE warehouse_id = ?) - (SELECT SUM(a3_16 * number) FROM products JOIN allproducts ON allproducts.id=products.allproduct_id WHERE warehouse_id = ? )) ,
    a3_18 = ((SELECT a3_18start FROM materials WHERE warehouse_id = ?) - (SELECT SUM(a3_18 * number) FROM products JOIN allproducts ON allproducts.id=products.allproduct_id WHERE warehouse_id = ? )) ,
    a3_20 = ((SELECT a3_20start FROM materials WHERE warehouse_id = ?) - (SELECT SUM(a3_20 * number) FROM products JOIN allproducts ON allproducts.id=products.allproduct_id WHERE warehouse_id = ? )) ,
    a3_22 = ((SELECT a3_22start FROM materials WHERE warehouse_id = ?) - (SELECT SUM(a3_22 * number) FROM products JOIN allproducts ON allproducts.id=products.allproduct_id WHERE warehouse_id = ? )) ,
    a3_25 = ((SELECT a3_25start FROM materials WHERE warehouse_id = ?) - (SELECT SUM(a3_25 * number) FROM products JOIN allproducts ON allproducts.id=products.allproduct_id WHERE warehouse_id = ? )) ,
    a3_28 = ((SELECT a3_28start FROM materials WHERE warehouse_id = ?) - (SELECT SUM(a3_28 * number) FROM products JOIN allproducts ON allproducts.id=products.allproduct_id WHERE warehouse_id = ? )) ,
    a3_32 = ((SELECT a3_32start FROM materials WHERE warehouse_id = ?) - (SELECT SUM(a3_32 * number) FROM products JOIN allproducts ON allproducts.id=products.allproduct_id WHERE warehouse_id = ? )) ,
    vr_3 = ((SELECT vr_3start FROM materials WHERE warehouse_id = ?) - (SELECT SUM(vr_3 * number) FROM products JOIN allproducts ON allproducts.id=products.allproduct_id WHERE warehouse_id = ? )) ,
    vr_5 = ((SELECT vr_5start FROM materials WHERE warehouse_id = ?) - (SELECT SUM(vr_5 * number) FROM products JOIN allproducts ON allproducts.id=products.allproduct_id WHERE warehouse_id = ? )) ,
    corner = ((SELECT cornerstart FROM materials WHERE warehouse_id = ?) - (SELECT SUM(corner * number) FROM products JOIN allproducts ON allproducts.id=products.allproduct_id WHERE warehouse_id = ? )) ,
    tube_57 = ((SELECT tube_57start FROM materials WHERE warehouse_id = ?) - (SELECT SUM(tube_57 * number) FROM products JOIN allproducts ON allproducts.id=products.allproduct_id WHERE warehouse_id = ? )) ,
    simp_zaklad = ((SELECT simp_zakladstart FROM materials WHERE warehouse_id = ?) - (SELECT SUM(simp_zaklad * number) FROM products JOIN allproducts ON allproducts.id=products.allproduct_id WHERE warehouse_id = ? )) ,
    k7 = ((SELECT k7start FROM materials WHERE warehouse_id = ?) - (SELECT SUM(k7 * number) FROM products JOIN allproducts ON allproducts.id=products.allproduct_id WHERE warehouse_id = ? )) ,
    comp_zaklad = ((SELECT comp_zakladstart FROM materials WHERE warehouse_id = ?) - (SELECT SUM(comp_zaklad * number) FROM products JOIN allproducts ON allproducts.id=products.allproduct_id WHERE warehouse_id = ? )) 
  WHERE warehouse_id = ?`, 
[
  warehouse_id,
  warehouse_id,
  warehouse_id,
  warehouse_id,
  warehouse_id,
  warehouse_id,
  warehouse_id,
  warehouse_id,
  warehouse_id,
  warehouse_id,
  warehouse_id,
  warehouse_id,
  warehouse_id,
  warehouse_id,
  warehouse_id,
  warehouse_id,
  warehouse_id,
  warehouse_id,
  warehouse_id,
  warehouse_id,
  warehouse_id,
  warehouse_id,
  warehouse_id,
  warehouse_id,
  warehouse_id,
  warehouse_id,
  warehouse_id,
  warehouse_id,
  warehouse_id,
  warehouse_id,
  warehouse_id,
  warehouse_id,
  warehouse_id,
  warehouse_id,
  warehouse_id,
  warehouse_id,
  warehouse_id,
  warehouse_id,
  warehouse_id,
  warehouse_id,
  warehouse_id,
  warehouse_id,
  warehouse_id,
  warehouse_id,
  warehouse_id,
  warehouse_id,
  warehouse_id,
  warehouse_id,
  warehouse_id,
  warehouse_id,
  warehouse_id,
  warehouse_id,
  warehouse_id,
  warehouse_id,
  warehouse_id,
  warehouse_id,
  warehouse_id,
  warehouse_id,
  warehouse_id,
  warehouse_id,
  warehouse_id
  
]);}
//	await pool.query('UPDATE materials SET a3_12 = ((SELECT a3_12start FROM materials WHERE warehouse_id = ?) - (SELECT SUM(a3_12 * number) FROM products WHERE warehouse_id = ?))', [warehouse_id,warehouse_id ]);

module.exports = { updateMaterials };